module.exports = {
  'Object': [
    'prototype',
  ],
  'Object.prototype': [
    'constructor',
    'hasOwnProperty',
    'isPrototypeOf',
    'propertyIsEnumerable',
    'toLocaleString',
    'toString',
    'valueOf',
  ],
  'Array': [
  ],
  'Array.prototype': [
    'concat',
    'join',
    'length',
    'pop',
    'push',
    'reverse',
    'shift',
    'slice',
    'sort',
    'splice',
    'unshift',
  ],
  'Function': [
  ],
  'Function.prototype': [
    'apply',
    'call',
    'length',
  ],
  'Boolean': [
  ],
  'Boolean.prototype': [
  ],
  'Number': [
    'MAX_VALUE',
    'MIN_VALUE',
    'NEGATIVE_INFINITY',
    'NaN',
    'POSITIVE_INFINITY',
  ],
  'Number.prototype': [
    'toExponential',
    'toFixed',
    'toPrecision',
  ],
  'String': [
    'fromCharCode',
  ],
  'String.prototype': [
    'charAt',
    'charCodeAt',
    'concat',
    'indexOf',
    'lastIndexOf',
    'length',
    'localeCompare',
    'match',
    'replace',
    'search',
    'slice',
    'split',
    'substring',
    'toLocaleLowerCase',
    'toLocaleUpperCase',
    'toLowerCase',
    'toUpperCase',
  ],
  'Date': [
    'UTC',
    'parse',
  ],
  'Date.prototype': [
    'getDate',
    'getDay',
    'getFullYear',
    'getHours',
    'getMilliseconds',
    'getMinutes',
    'getMonth',
    'getSeconds',
    'getTime',
    'getTimezoneOffset',
    'getUTCDate',
    'getUTCDay',
    'getUTCFullYear',
    'getUTCHours',
    'getUTCMilliseconds',
    'getUTCMinutes',
    'getUTCMonth',
    'getUTCSeconds',
    'setDate',
    'setFullYear',
    'setHours',
    'setMilliseconds',
    'setMinutes',
    'setMonth',
    'setSeconds',
    'setTime',
    'setUTCDate',
    'setUTCFullYear',
    'setUTCHours',
    'setUTCMilliseconds',
    'setUTCMinutes',
    'setUTCMonth',
    'setUTCSeconds',
    'toDateString', 
    'toLocaleDateString',
    'toLocaleString',
    'toLocaleTimeString',
    'toTimeString', 
    'toUTCString',
  ],
  'Math': [
    'E',
    'LN10',
    'LN2',
    'LOG10E',
    'LOG2E',
    'PI',
    'SQRT1_2',
    'SQRT2',
    'abs',
    'acos',
    'asin',
    'atan',
    'atan2',
    'ceil',
    'cos',
    'exp',
    'floor',
    'log', 
    'max',
    'min',
    'pow',
    'random',
    'round',
    'sin',
    'sqrt',
    'tan',
  ],
  'Math.prototype': [
  ],
  'RegExp': [
  ],
  'RegExp.prototype': [
    'exec',
    'global',
    'ignoreCase',
    'lastIndex',
    'multiline',
    'source',
    'test',
  ],
  'Error': [
  ],
  'Error.prototype': [
    'name',
    'message',
  ],
  'RangeError': [
  ],
  'RangeError.prototype': [
    'name',
    'message',
  ],
  'ReferenceError': [
  ],
  'ReferenceError.prototype': [
    'name',
    'message',
  ],
  'SyntaxError': [
  ],
  'SyntaxError.prototype': [
    'name',
    'message',
  ],
  'TypeError': [
  ],
  'TypeError.prototype': [
    'name',
    'message',
  ],
  'URIError': [
  ],
  'URIError.prototype': [
    'name',
    'message',
  ],
};

